name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Build project
        run: cargo build --verbose

      - name: Run unit & integration tests
        run: cargo test --all --verbose

  release-artifact:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Archive project
        run: zip -r weather-tracking-system.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: weather-artifact
          path: weather-tracking-system.zip

